name: ci
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libsdl2-dev

      - name: build
        run: make

      - name: test
        run: make test
